#  Pytest for unit tests
[pytest]
pythonpath = .          # add project root to sys.path before running - prevents fail
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short